### ISSUE TITLE
window.location.origin and IE10

### ISSUE THREAD

**Issue by filchos** [virtualidentityag/conditional-resource-loader#13]
The current implementation doesn’t work with IE < 11 since the property **window.location.origin** is used twice in **resourceLoader.js**. This property needs at least IE 11.

https://www.w3schools.com/jsref/prop_loc_origin.asp
http://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/

**Comment by timomayer** [comment]
Hey @filchos thanks for your contribution :)
Do you think you can provide a pull request to fix that issue? Would really appreciate that :)

**Comment by filchos** [comment]
Hej @timomayer, I fixed the bug in a local branch by adding a polyfill but I’m not allowed to push the branch.

I added a patch with the changes. (Had to zip it due to Github not supporting file the .patch extension)

[origin-fix.patch.zip](https://github.com/virtualidentityag/conditional-resource-loader/files/1024563/origin-fix.patch.zip)

**Comment by davelosert** [comment]
@filchos : You can usually create a PR by Forking the repository and pushing to a branch of yours.
Github usually then even offers a button on your repository to create a pull request of that branch to the original repo. That is easier than sending around zip files.

**Comment by janrembold** [comment]
Please check this pull request https://github.com/virtualidentityag/conditional-resource-loader/pull/14 if it fits your needs. 

This includes the fix from http://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/
