### ISSUE TITLE
Move to Webpack?

### ISSUE THREAD

**Issue by davelosert** [virtualidentityag/conditional-resource-loader#3]
I just saw this repository of ours and that you guys are actively working on it.

I dont know if I truly understood the purpose of exactly THIS Project, but for me it definitly sounds like it does the same thing as [Webpack](https://github.com/webpack/webpack) - meaning bundling an application with the ability to conditionally load different modules (and even do this lazily).

If so, i would strongly recommend to use Webpack as it is already more sophisticated and further developed - and you can use it out of the box. ;)

Just thought i mention it here.

**Comment by smohadjer** [comment]
I don't think Webpack does what is done here. This loader allows us to add full-fledged HTML snippets (you can call them modules or components) to a web page without changing anything else in the page. When a page loads, loader searches the DOM for these snippets and then loads their resources (js and/or css) and then initializes the snippet. This is not something used during build process like Webpack.
